// import { AuthProvider } from "../contexts/Auth/AuthContext";
import { AuthProvider } from "@/contexts/Auth/AuthContext";
import "./globals.css";

export const metadata = {
  title: "Next.jssadasdas",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
